In [1]:
import numpy as np
import pandas as pd
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [2]:
ages = np.array([13,25,19])
series1 = pd.Series(ages,index=['Emma', 'Swetha', 'Serajh'])
print(series1)

Emma      13
Swetha    25
Serajh    19
dtype: int64


In [3]:
np.mean([1, 2, 3, 4, 5])

3.0

In [4]:
np.dtype(float).itemsize # in bytes

8

In [5]:
np.ones(10, dtype='int') # generates 10 integer ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.random.random(10) # uniform on [0,1]

array([0.35964237, 0.54301145, 0.90570676, 0.43287668, 0.04121097,
       0.73153192, 0.00530837, 0.82544201, 0.23313006, 0.07442674])

In [8]:
normal_array = np.random.randn(1000)
print("The sample mean and standard devation are %f and %f, respectively." %(np.mean(normal_array), np.std(normal_array)))

The sample mean and standard devation are 0.005565 and 1.012976, respectively.


In [9]:
my_identity = np.eye(3)
print(my_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# create a dataframe
dframe = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['India', 'USA', 'China', 'Russia'])
#compute a formatted string from each floating point value in frame
changefn = lambda x: '%.2f' % x
# Make changes element-wise
dframe['d'].map(changefn)

India     -0.63
USA        0.57
China     -0.71
Russia     0.35
Name: d, dtype: object

In [11]:
# Create a sample dataframe
school = pd.DataFrame({'A': ['Jay', 'Usher', 'Nicky', 'Romero', 'Will'], 
      'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'], 
      'C': [26, 22, 20, 23, 24]})
# Lets create a pivot table to segregate students based on age and course
table = pd.pivot_table(school, values ='A', index =['B', 'C'], 
                         columns =['B'], aggfunc = np.sum, fill_value="Not Available") 
  
table

B                 Graduate        Masters
B        C                               
Graduate 20          Nicky  Not Available
         22          Usher  Not Available
         24           Will  Not Available
Masters  23  Not Available         Romero
         26  Not Available            Jay

In [12]:
pd.Index(["foo", "bar", "baz"]) == "foo"

array([ True, False, False])

In [23]:
pd.notna('dog')

True

In [24]:
pd.notna(pd.NA)

False

In [15]:
a = np.array(["foo", "foo", "foo", "foo", "bar", "bar",
              "bar", "bar", "foo", "foo", "foo"], dtype=object)
b = np.array(["one", "one", "one", "two", "one", "one",
              "one", "two", "two", "two", "one"], dtype=object)
c = np.array(["dull", "dull", "shiny", "dull", "dull", "shiny",
              "shiny", "dull", "shiny", "shiny", "shiny"],
             dtype=object)
pd.crosstab(a, [b, c], rownames=['a'], colnames=['b', 'c'])

b    one        two      
c   dull shiny dull shiny
a                        
bar    1     2    1     0
foo    2     2    1     2

In [16]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]), 3)

[(0.994, 3.0], (5.0, 7.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (0.994, 3.0]]
Categories (3, interval[float64]): [(0.994, 3.0] < (3.0, 5.0] < (5.0, 7.0]]

In [17]:
df1 = pd.DataFrame({'left': ['foo', 'bar']})
df2 = pd.DataFrame({'right': [7, 8]})
df1     #pandas.merge function

left
0  foo
1  bar

In [18]:
pd.qcut(range(5), 3, labels=["good", "medium", "bad"])

['good', 'good', 'medium', 'bad', 'bad']
Categories (3, object): ['good' < 'medium' < 'bad']

In [19]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [20]:
pd.unique(pd.Series([2, 1, 3, 3]))

array([2, 1, 3])

In [27]:
pd.isna('dog')

False

In [28]:
pd.isna(pd.NA)

True

In [29]:
pd.isna(np.nan)

True

In [30]:
codes, uniques = pd.factorize(['b', 'b', 'a', 'c', 'b'])
codes

array([0, 0, 1, 2, 0])