In [13]:
import numpy as np
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [4]:
np.mean([1, 2, 3, 4, 5])

3.0

In [5]:
np.dtype(float).itemsize # in bytes

8

In [6]:
np.ones(10, dtype='int') # generates 10 integer ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.random.random(10) # uniform on [0,1]

array([0.92966142, 0.34545763, 0.55502   , 0.06286873, 0.5570475 ,
       0.12660064, 0.72445243, 0.4280288 , 0.65100163, 0.53891555])

In [9]:
normal_array = np.random.randn(1000)
print("The mean and standard devation are %f and %f, respectively." %(np.mean(normal_array), np.std(normal_array)))

The mean and standard devation are -0.013215 and 0.982168, respectively.


In [10]:
my_identity = np.eye(3)
print(my_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
import numpy
 
arr1 = numpy.arange(4)
print('Elements of an array1:\n',arr1)
 
arr2 = numpy.arange(4,8)
print('Elements of an array2:\n',arr2)
 
res1 = arr1.reshape(2,2)
print('Reshaped array with 2x2 dimensions:\n',res1)
 
res2 = arr2.reshape(2,2)
print('Reshaped array with 2x2 dimensions:\n',res2)
 


Elements of an array1:
 [0 1 2 3]
Elements of an array2:
 [4 5 6 7]
Reshaped array with 2x2 dimensions:
 [[0 1]
 [2 3]]
Reshaped array with 2x2 dimensions:
 [[4 5]
 [6 7]]


In [15]:
import numpy
  
res =  numpy.char.add(['Praveena'],[' Sharmila'])
 
print("Concatenating two strings:\n",res)
 
print("Capitalizing the string: ",numpy.char.capitalize('tactlabs'))
 
print("Converting to lower case: ",numpy.char.lower('PRAVEENA'))
 
print("Converting to UPPER case: ",numpy.char.upper('sharmila'))
 
print("Replacing string within a string: ",numpy.char.replace ('Praveena and AA', 'AA', 'Sharmila'))


Concatenating two strings:
 ['Praveena Sharmila']
Capitalizing the string:  Tactlabs
Converting to lower case:  praveena
Converting to UPPER case:  SHARMILA
Replacing string within a string:  Praveena and Sharmila


In [17]:
import numpy as np 
x = np.array([10,20,30,4,50,60]) 
 
med = np.median(x)
print("Median value of array: \n",med)
 
mean = np.mean(x)
print("Mean value of array: \n",mean)
 
avg = np.average(x)
print("Average value of array: \n",avg)
 
std = np.std(x)
print("Standard deviation value of array: \n",std)


Median value of array: 
 25.0
Mean value of array: 
 29.0
Average value of array: 
 29.0
Standard deviation value of array: 
 20.2895703913776


In [18]:
import numpy as np 
x = np.arange(4) 
print("Elements of array 'x':\n",x)
 
y = np.arange(4,8) 
print("Elements of array 'y':\n",y)
 
add = np.add(x,y)
print("Addition of x and y:\n",add)
 
subtract = np.subtract(x,y)
print("Subtraction of x and y:\n",subtract)
 
mul = np.multiply(x,y)
print("Multiplication of x and y:\n",mul)

Elements of array 'x':
 [0 1 2 3]
Elements of array 'y':
 [4 5 6 7]
Addition of x and y:
 [ 4  6  8 10]
Subtraction of x and y:
 [-4 -4 -4 -4]
Multiplication of x and y:
 [ 0  5 12 21]


In [2]:
import numpy as np
an_array = np.genfromtxt("amazon.csv", dtype=None, encoding=None, delimiter=",")

print(an_array)

[['Amazon' 'Revenue']
 ['Prime' '90']
 ['Kindle' '80']
 ['Onlinestore' '75']
 ['Echo' '60']
 ['Alexa' '53']
 ['Webservies' '90']]
